In [1]:
import numpy as np

# First matrix
A = np.array([[1, 2],
              [3, 4]])

# Second matrix
B = np.array([[5, 6],
              [7, 8]])

# Addition
addition = A + B

# Subtraction
subtraction = A - B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition of matrices:")
print(addition)

print("\nSubtraction of matrices:")
print(subtraction)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Addition of matrices:
[[ 6  8]
 [10 12]]

Subtraction of matrices:
[[-4 -4]
 [-4 -4]]
