In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Matrix:")
print(matrix)
print("\nShape of the matrix:")
print(matrix.shape)

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape of the matrix:
(3, 4)
