In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Maximum value:")
print(np.max(matrix))
print("\nSine of each element:")
print(np.sin(matrix))
print("\nMaximum value in each column:")
print(np.max(matrix, axis=0))
print("\nMaximum value in each row:")
print(np.max(matrix, axis=1))

Maximum value:
9

Sine of each element:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

Maximum value in each column:
[7 8 9]

Maximum value in each row:
[3 6 9]
