In [1]:
import numpy as np

# Create a matrix with all values as 1
matrix = np.array([[1, 1, 1],
                   [1, 1, 1],
                   [1, 1, 1]])

# Print the matrix
print("Matrix:")
print(matrix)

# Find the rank of the matrix
print("\nRank of Matrix:")
print(np.linalg.matrix_rank(matrix))


# Create a full rank matrix
full_rank = np.array([[1, 2],
                      [3, 4]])

# Print the full rank matrix
print("\nFull Rank Matrix:")
print(full_rank)

# Find the rank of full rank matrix
print("\nRank of Full Rank Matrix:")
print(np.linalg.matrix_rank(full_rank))

Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Rank of Matrix:
1

Full Rank Matrix:
[[1 2]
 [3 4]]

Rank of Full Rank Matrix:
2
