In [1]:
import numpy as np

# Create matrices
matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])

# Print the original matrices
print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

# Flatten Matrix A using flatten()
print("\nFlatten Matrix A:")
print(matrix_a.flatten())

# Flatten Matrix A using reshape()
print("\nFlatten Matrix A using reshape(1,-1):")
print(matrix_a.reshape(1, -1))

# Combine matrices and flatten using ravel()
print("\nFlatten Combined Matrices using ravel():")
print(np.ravel([matrix_a, matrix_b]))

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Flatten Matrix A:
[1 2 3 4]

Flatten Matrix A using reshape(1,-1):
[[1 2 3 4]]

Flatten Combined Matrices using ravel():
[1 2 3 4 5 6 7 8]
