In [1]:
import numpy as np

# Create first matrix
matrix1 = np.array([
    [1, 2],
    [3, 4]
])

# Create second matrix
matrix2 = np.array([
    [5, 6],
    [7, 8]
])

# Multiply the matrices
result = np.dot(matrix1, matrix2)

# Display the matrices
print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of Matrix Multiplication:")
print(result)

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Result of Matrix Multiplication:
[[19 22]
 [43 50]]
