In [1]:
import numpy as np
vector = np.zeros(shape=5)
print("Zeros Vector:")
print(vector)
ones_matrix = np.ones(shape=(3, 3))
print("\nOnes Matrix:")
print(ones_matrix)
full_matrix = np.full(shape=(3, 3), fill_value=1)
print("\nFull Matrix:")
print(full_matrix)

Zeros Vector:
[0. 0. 0. 0. 0.]

Ones Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]]
