In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("Original Matrix:")
print(matrix)
print("\nReshape to (2, 6):")
print(matrix.reshape(2, 6))
print("\nReshape to (1, -1):")
print(matrix.reshape(1, -1))
print("\nReshape to (12,):")
print(matrix.reshape(12))

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshape to (2, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshape to (1, -1):
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]

Reshape to (12,):
[ 1  2  3  4  5  6  7  8  9 10 11 12]
