In [1]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Print the original matrix
print("Original Matrix:")
print(matrix)

# Transpose the matrix
print("\nTranspose of Matrix:")
print(matrix.T)

# Transpose a vector
print("\nTranspose of Vector:")
print(np.array([[1, 2, 3, 4, 5, 6]]).T)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of Vector:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
